package projects.automaton

import csstype.Clear
import csstype.ObjectFit
import csstype.pct
import csstype.px
import emotion.react.css
import react.FC
import react.Props
import react.dom.html.ReactHTML
import react.dom.html.ReactHTML.a
import react.dom.html.ReactHTML.div
import react.dom.html.ReactHTML.strong

//TODO move to utils
external interface ImageProps : Props {
    var imageSource: String
    var altText: String
    var copyrightSource: String
    var copyrightMessage: String
}

private val image: FC<ImageProps>
    get() = FC { props ->
        div {
            div {
                ReactHTML.img {
                    css {
                        width = 100.pct
                        height = 100.pct
                        maxWidth = 300.px
                        objectFit = ObjectFit.contain
                    }
                    src = props.imageSource
                    alt = props.altText
                }
            }
            div {
                ReactHTML.a {
                    href = props.copyrightSource
                    +props.copyrightMessage
                }
            }
        }
    }

val About = FC<Props> {
    div {
        strong {
            +"Nature meets Math"
        }
        div {
            image {
                imageSource = "/static/shell.jpg"
                altText = "A Conus textile shell similar in appearance to Rule 30"
                copyrightSource = "https://creativecommons.org/licenses/by-sa/3.0/"
                copyrightMessage = "Copyright (c) 2005 Richard Ling"
            }
        }
        div {
            css {
                clear = Clear.left
            }
            +"This project shows "
            a {
                href = "https://en.wikipedia.org/wiki/Elementary_cellular_automaton"
                +"Elementary Cellular Automaton"
            }
            +" in which each new line is generated by applying the ruleset to the current line."
        }
        div {
            +"It defaults to "
            a {
                href = "https://en.wikipedia.org/wiki/Rule_30"
                +"Rule 30"
            }
            +", which displays chaotic behavior despite only following simple mathematical rules."
        }
    }
}